[versions]
dotenv-kotlin = "6.5.1"
koog-agents = "0.3.0"
kotlin-logging-jvm = "7.0.3"
slf4j-simple = "2.0.3"

[libraries]
dotenv-kotlin = { group = "io.github.cdimascio", name = "dotenv-kotlin", version.ref = "dotenv-kotlin" }
koog-agents = { group = "ai.koog", name = "koog-agents", version.ref = "koog-agents" }
kotlin-logging-jvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j-simple" }

[plugins]
